language: python
python:
  - "3.6"
before_install:
  - sudo apt-get -y install python3-pip git
  - pip3 install coveralls==1.3.0
addons:
  apt:
    update: true
install:
  - pip3 install pycodestyle==2.4.0
  - pip3 install flake8==3.6.0
script:
  - ./bin/run-ci
after_script:
  - echo Collecting coverage information
  - sed -i -e "s@/app/@$PWD/@g" ./tests/coverage/.coverage
  - cat ./tests/coverage/.coverage
  - coveralls
branches:
  only:
  - develop
